gpu_id = [4, 5, 6, 7]
# DATA = '/home/ubuntu/recognition/data/masks_clean/HAIR/'
DATA = '/home/dev/Documents/HAIR/'
CHECKPOINT_DIR = 'checkpoints'
USE_MATPLOTLIB_VIS = False
RESIZE_TO = 512
PER_ITER_LOSS = 'per_iter_loss'
PER_EPOCH_LOSS = 'per_epoch_loss'
BASE_BATCH_SIZE = 4
BATCH_SIZE = len(gpu_id) * BASE_BATCH_SIZE
